services:
  - type: web
    name: gangneung-lifesaver-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "sh start.sh"
    autoDeploy: false
    buildFilter:
      paths:
        - main.py
        - nationwide_lifesavers_coordinates_only.json