services:
  - type: web
    name: lifesaver-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    plan: free
    envVars:
      - key: PORT
        value: 8000
